# Development-only generation/checking; never creates a ZIP, tag or release.
[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = 'Stop'
$repository = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
. (Join-Path $repository 'WinImgNormalizer.ps1')
$applicationVersion = Get-WinImgVersion
if ($applicationVersion -notmatch '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$') {
    throw 'Application version must be a three-part semantic version.'
}
$notes = [IO.File]::ReadAllText((Join-Path $repository 'docs/release/NOTES.md')).Replace("`r`n", "`n").TrimEnd()
$changelog = "# Changelog`n`n<!-- Generated by tools/release/Update-ReleaseMetadata.ps1; edit docs/release/NOTES.md. -->`n`n## $applicationVersion (unreleased)`n`n$notes`n"
$metadata = [ordered]@{
    schema_version = 1
    product = 'WinImgNormalizer'
    version = $applicationVersion
    version_source = 'WinImgNormalizer.ps1:Get-WinImgVersion'
    release_state = 'unreleased'
    proposed_tag = 'v' + $applicationVersion
    tag = $null
    release_date = $null
    release_url = $null
    asset_filename = $null
    asset_bytes = $null
    asset_sha256 = $null
    download_url = $null
    license = 'MIT'
    author = 'Janne Vuorela'
    repository_url = 'https://github.com/PikkuJanne/WinImgNormalizer'
    release_notes_file = 'CHANGELOG.md'
    requirements_file = 'README.md'
}
$metadataText = ($metadata | ConvertTo-Json -Depth 4 -Compress) + "`n"
$outputs = [ordered]@{ 'CHANGELOG.md' = $changelog; 'release-metadata.json' = $metadataText }
$encoding = [Text.UTF8Encoding]::new($false)
foreach ($name in $outputs.Keys) {
    $path = Join-Path $repository $name
    # Refuse linked output files or parents before checking or replacing bytes.
    $current = Get-Item -LiteralPath $repository -Force
    while ($null -ne $current) {
        if (($current.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw 'Release metadata directory crosses a reparse point.' }
        $current = $current.Parent
    }
    if (Test-Path -LiteralPath $path) {
        $item = Get-Item -LiteralPath $path -Force
        if ($item -isnot [IO.FileInfo] -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { throw 'Release metadata output must be a regular file.' }
    }
    if ($Check) {
        if (-not [IO.File]::Exists($path) -or
            [Convert]::ToBase64String([IO.File]::ReadAllBytes($path)) -cne [Convert]::ToBase64String($encoding.GetBytes($outputs[$name]))) {
            throw ('Generated release metadata is stale or missing: ' + $name + '. Run tools/release/Update-ReleaseMetadata.ps1.')
        }
    } else {
        [IO.File]::WriteAllText($path, $outputs[$name], $encoding)
    }
}
Write-Output ('Release metadata {0}: WinImgNormalizer {1} (unreleased)' -f $(if ($Check) { 'verified' } else { 'generated' }), $applicationVersion)
